---
- name: Make users and install packages
  hosts: 192.168.5.48
  vars:
   users:
    - username: ops1
      groups: webadmin
    - username: ops2
      groups: webadmin
   packages:
    - httpd
    - firewalld
  tasks: 
   - name: Create a group
     group: 
      name: webadmin
      state: present
   - name: Create user accounts
     user:
      name: "{{ item.username }}"
      groups: webadmin
     loop: "{{ users }}" 
   - name: Install the packages
     yum:
      name: "{{ packages }}"
      state: present
